definition = {
    'bitcoin':'''Le Bitcoin (BTC) (de l'anglais bit : unité d'information binaire et coin "pièce de monnaie") est une cryptomonnaie autrement appelée monnaie cryptographique. Dans le cas de la dénomination unitaire, on l'écrit "bitcoin" et, dans le cas du système de paiement pair-à-pair on l'écrit "Bitcoin". L'idée fut présentée pour la première fois en novembre 2008 par une personne, ou un groupe de personnes, sous le pseudonyme de Satoshi Nakamoto. Le code source de l'implémentation de référence fut quant à lui publié en 2009. Le G20 considère que le Bitcoin est un "crypto-actif". Ce terme "crypto-actif" fait alors référence à "des actifs virtuels stockés sur un support électronique permettant à une communauté d'utilisateurs les acceptant en paiement de réaliser des transactions sans avoir à recourir à la monnaie légale".''',
    'ethereum':"Ethereum (prononcé /e.tɛ.ʁœm/) est un protocole d'échanges décentralisés permettant la création par les utilisateurs de contrats intelligents grâce à un langage Turing-complet. Ces contrats intelligents sont basés sur un protocole informatique permettant de vérifier ou de mettre en application un contrat mutuel. Ils sont déployés et consultables publiquement dans une blockchain.",
    'ripple':'''Ripple est un système de règlement brut en temps réel (RBTR), un marché des changes et un réseau d'envois de fonds par la société Ripple. Aussi appelé le Ripple Transaction Protocol (RTXP) ou protocole Ripple, il est construit sur un protocole internet distribué et open source, un registre de consensus et une monnaie native appelée XRP (ripples). Lancé en 2012, le réseau Ripple vise à permettre des « transactions financières mondiales sécurisées, instantanées et presque gratuites, de toute taille sans rejets de débit ». Il prend en charge n'importe quelle monnaie fiduciaire, crypto-monnaie, commodité ou toute autre unité de valeur tels que miles aériens, minutes mobiles. À sa base, Ripple repose sur une base de données publique partagée ou registre, qui utilise un processus de consensus permettant des paiements, échanges et envois de fonds dans un processus distribué.''',
    'bitcoin_cash':'''Bitcoin Cash (abrégé BCH ou BCC) est une crypto-monnaie inspirée de la crypto-monnaie Bitcoin. Bitcoin Cash repose sur la technologie de base de données séquentielle et distribuée appelée blockchain, telle qu'elle fut décrite en 2008 par Satoshi Nakamoto. Bitcoin Cash a été créé pour augmenter la capacité de la chaîne afin de subvenir à la croissance du nombre d'utilisateurs. Cela nécessita une bifurcation (hard fork) du protocole Bitcoin qui a eu lieu le 1er août 2017. ''',
    'bitcoin_sv':'''Bitcoin SV est un dérivé de Bitcoin Cash (BCH). Il tente de restaurer le protocole Bitcoin d'origine défini par la version 0.1 de Bitcoin.''',
    'tether':'''Tether (abrégé UDST) est une crypto-monnaie, de type stablecoin, émise par la société Tether Limited. Historiquement, la société affirmait que chaque coin était adossée à un dollar américain, mais depuis le 14 mars 2019, elle a modifié son adossement pour inclure les prêts aux entreprises affiliées. En avril 2019, le procureur général de l'État de New York accuse la plateforme d'échange Bitfinex d'utiliser les Tether pour masquer l'absence de 850 millions de dollars depuis la mi-2018. C'est pour ces différents points que le Tether est controversé.''',
    'litecoin':'''Litecoin (symbole monétaire : Ł ; sigle : LTC) est une monnaie électronique distribuée (crypto-monnaie) sous licence libre (MIT License), inspirée par et techniquement similaire à Bitcoin. Litecoin peut fonctionner avec les mêmes logiciels « d’exploitation minière » que bitcoin. Chaque Litecoin est divisé en cent millions d'unités plus petites, définies par huit décimales. Le Litecoin est une marque déposée par la fondation éponyme 111 North Bridge Road Singapour.''',
    'eos':'''EOS est une cryptomonnaie conçue pour la prise en charge d'applications à grande échelle. L'envoi ou la réception d'EOS n'occasionnent aucun frais. Le protocole rémunère les entités qui exploitent le réseau avec de nouveaux EOS en recourant à l'inflation pour les frais de transaction.''',
    'binance_coin':'''Binance Coin (BNB) is the cryptocurrency of the Binance platform. The name "Binance" is a combination of binary and finance. As of 2019, many businesses accept BNB as a form of payment.''',
    'cardano':'''Cardano est une cryptomonnaie doublée d'une plate-forme informatique décentralisée. Cardano comporte un algorithme de consensus spécifique (appelé Ouroboros) qui valide les transactions en minimisant les coûts énergétiques.'''
}

lien = {
     'bitcoin':'''https://fr.wikipedia.org/wiki/Bitcoin''',
     'ethereum':'''https://fr.wikipedia.org/wiki/Ethereum''',
     'ripple':'''https://fr.wikipedia.org/wiki/Ripple_(protocole_de_paiement)''',
     'bitcoin_cash':'''https://fr.wikipedia.org/wiki/Bitcoin_Cash''',
     'bitcoin_sv':'''https://www.coinbase.com/price/bitcoin-sv''',
     'tether':'''https://fr.wikipedia.org/wiki/Tether''',
     'litecoin':'''https://fr.wikipedia.org/wiki/Litecoin''',
     'eos':'''https://www.coinbase.com/price/eos?locale=fr''',
     'binance_coin':'''https://www.coinbase.com/price/binance-coin?locale=fr''',
     'cardano':'''https://www.coinbase.com/price/cardano?locale=fr''',
}